# Generated by Django 4.2.7 on 2025-12-19 11:30

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WhyCashMattersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('intro', models.CharField(max_length=250)),
                ('body', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', icon='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock(help_text='Enter the quote text', required=True)), ('name', wagtail.blocks.CharBlock(help_text="Person's name", required=False)), ('job_title', wagtail.blocks.CharBlock(help_text='Job title', required=False)), ('company', wagtail.blocks.CharBlock(help_text='Company name', required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True)),
                ('title_position', models.CharField(blank=True, help_text='Position of the title', max_length=50)),
                ('page_header', wagtail.fields.RichTextField(blank=True, help_text='Optional page header content')),
                ('featured', models.BooleanField(default=False, help_text='Feature post (requires tall thumbnail)')),
                ('double_width', models.BooleanField(default=False, help_text='Double width on home page (requires wide thumbnail)')),
                ('white_text', models.BooleanField(default=False, help_text='White text for darker images')),
                ('hide_title', models.BooleanField(default=False, help_text='Hide title when using text in thumbnail')),
                ('color', models.CharField(blank=True, help_text='Color option', max_length=50)),
                ('cm_watermark', models.BooleanField(default=False, help_text='CM Watermark?')),
                ('alternative_text', models.CharField(blank=True, help_text='Alternative text', max_length=250)),
                ('twitter_body', models.TextField(blank=True, help_text='Twitter body text')),
                ('vimeo_id', models.CharField(blank=True, help_text='Vimeo Video ID', max_length=50)),
                ('source_link', models.URLField(blank=True, help_text="Link to the article's source")),
                ('facts', wagtail.fields.StreamField([('fact', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Fact title', required=True)), ('related_sector', wagtail.blocks.CharBlock(help_text='Related sector', required=True)), ('background_image', wagtail.images.blocks.ImageChooserBlock(help_text='Background image', required=False)), ('icon', wagtail.images.blocks.ImageChooserBlock(help_text='Icon (234x188 min)', required=False)), ('color', wagtail.blocks.CharBlock(help_text='Color theme', required=False)), ('text', wagtail.blocks.TextBlock(help_text='Main fact text', required=True)), ('reveal_title', wagtail.blocks.CharBlock(help_text='Reveal section title', required=False)), ('reveal_text', wagtail.blocks.TextBlock(help_text='Reveal section text', required=False))]))], blank=True, help_text='Add facts with reveal functionality', use_json_field=True)),
                ('article_types', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select article types', to='blog.articletype')),
                ('icon', models.ForeignKey(blank=True, help_text='Choose an icon image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('locations', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select locations', to='blog.location')),
                ('page_header_image', models.ForeignKey(blank=True, help_text='Choose an image for the page header', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('sectors', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select sectors', to='blog.sector')),
                ('tall_thumbnail', models.ForeignKey(blank=True, help_text='Tall thumbnail (540px x 750px) - used on Section Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('wide_thumbnail', models.ForeignKey(blank=True, help_text='Wide thumbnail (1140px x 750px) - used on Home Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SupportPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_header_title', models.CharField(blank=True, help_text='Optional. Defaults to page title if empty.', max_length=200)),
                ('description_title', models.CharField(blank=True, help_text='Description title', max_length=200)),
                ('description_content', wagtail.fields.RichTextField(blank=True, help_text='Description content')),
                ('description_link', models.URLField(blank=True, help_text='Optional link for more information.')),
                ('introduction', wagtail.fields.RichTextField(blank=True, help_text='Introduction text')),
                ('media_contacts', wagtail.fields.RichTextField(blank=True, help_text='Media Contacts information')),
                ('members_only', wagtail.fields.RichTextField(blank=True, help_text='Members only content')),
                ('description_image', models.ForeignKey(blank=True, help_text='Choose an image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page_header_image', models.ForeignKey(blank=True, help_text='Page Header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('video_background_image', models.ForeignKey(blank=True, help_text='Background image for video section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('video_file', models.ForeignKey(blank=True, help_text='MP4 video file. Add background image for mobile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='KeyFactsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=250)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('key_facts', wagtail.fields.RichTextField(blank=True, help_text='List of key facts')),
                ('header_image', models.ForeignKey(blank=True, help_text='Choose a header image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('intro', models.CharField(max_length=250)),
                ('body', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', icon='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock(help_text='Enter the quote text', required=True)), ('name', wagtail.blocks.CharBlock(help_text="Person's name", required=False)), ('job_title', wagtail.blocks.CharBlock(help_text='Job title', required=False)), ('company', wagtail.blocks.CharBlock(help_text='Company name', required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True)),
                ('title_position', models.CharField(blank=True, help_text='Position of the title', max_length=50)),
                ('page_header', wagtail.fields.RichTextField(blank=True, help_text='Optional page header content')),
                ('featured', models.BooleanField(default=False, help_text='Feature post (requires tall thumbnail)')),
                ('double_width', models.BooleanField(default=False, help_text='Double width on home page (requires wide thumbnail)')),
                ('white_text', models.BooleanField(default=False, help_text='White text for darker images')),
                ('hide_title', models.BooleanField(default=False, help_text='Hide title when using text in thumbnail')),
                ('color', models.CharField(blank=True, help_text='Color option', max_length=50)),
                ('cm_watermark', models.BooleanField(default=False, help_text='CM Watermark?')),
                ('alternative_text', models.CharField(blank=True, help_text='Alternative text', max_length=250)),
                ('twitter_body', models.TextField(blank=True, help_text='Twitter body text')),
                ('vimeo_id', models.CharField(blank=True, help_text='Vimeo Video ID', max_length=50)),
                ('source_link', models.URLField(blank=True, help_text="Link to the article's source")),
                ('article_types', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select article types', to='blog.articletype')),
                ('icon', models.ForeignKey(blank=True, help_text='Choose an icon image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('locations', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select locations', to='blog.location')),
                ('page_header_image', models.ForeignKey(blank=True, help_text='Choose an image for the page header', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('sectors', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select sectors', to='blog.sector')),
                ('tall_thumbnail', models.ForeignKey(blank=True, help_text='Tall thumbnail (540px x 750px) - used on Section Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('wide_thumbnail', models.ForeignKey(blank=True, help_text='Wide thumbnail (1140px x 750px) - used on Home Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('intro', models.CharField(max_length=250)),
                ('body', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', icon='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('quote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock(help_text='Enter the quote text', required=True)), ('name', wagtail.blocks.CharBlock(help_text="Person's name", required=False)), ('job_title', wagtail.blocks.CharBlock(help_text='Job title', required=False)), ('company', wagtail.blocks.CharBlock(help_text='Company name', required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, use_json_field=True)),
                ('title_position', models.CharField(blank=True, help_text='Position of the title', max_length=50)),
                ('page_header', wagtail.fields.RichTextField(blank=True, help_text='Optional page header content')),
                ('featured', models.BooleanField(default=False, help_text='Feature post (requires tall thumbnail)')),
                ('double_width', models.BooleanField(default=False, help_text='Double width on home page (requires wide thumbnail)')),
                ('white_text', models.BooleanField(default=False, help_text='White text for darker images')),
                ('hide_title', models.BooleanField(default=False, help_text='Hide title when using text in thumbnail')),
                ('color', models.CharField(blank=True, help_text='Color option', max_length=50)),
                ('cm_watermark', models.BooleanField(default=False, help_text='CM Watermark?')),
                ('alternative_text', models.CharField(blank=True, help_text='Alternative text', max_length=250)),
                ('twitter_body', models.TextField(blank=True, help_text='Twitter body text')),
                ('vimeo_id', models.CharField(blank=True, help_text='Vimeo Video ID', max_length=50)),
                ('source_link', models.URLField(blank=True, help_text="Link to the article's source")),
                ('article_types', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select article types', to='blog.articletype')),
                ('icon', models.ForeignKey(blank=True, help_text='Choose an icon image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('locations', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select locations', to='blog.location')),
                ('page_header_image', models.ForeignKey(blank=True, help_text='Choose an image for the page header', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('sectors', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select sectors', to='blog.sector')),
                ('tall_thumbnail', models.ForeignKey(blank=True, help_text='Tall thumbnail (540px x 750px) - used on Section Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('wide_thumbnail', models.ForeignKey(blank=True, help_text='Wide thumbnail (1140px x 750px) - used on Home Page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
