# Generated by Django 4.2.7 on 2025-12-20 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(blank=True, help_text='Author biography')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter URL')),
                ('profile_image', models.ForeignKey(blank=True, help_text="Author's profile image", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
