# Generated by Django 4.2.7 on 2025-12-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='author',
            field=models.CharField(blank=True, help_text='Author name', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='author',
            field=models.CharField(blank=True, help_text='Author name', max_length=100),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
