# Generated by Django 4.2.7 on 2025-12-25 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('blog', '0003_articlepage_author_blogpage_author_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='author_image',
            field=models.ForeignKey(blank=True, help_text='Author profile picture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='author_image',
            field=models.ForeignKey(blank=True, help_text='Author profile picture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
