# Generated by Django 4.2.7 on 2025-12-29 05:44
# Note: This migration is state-only as the database already has all the schema changes

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('blog', '0004_articlepage_author_image_blogpage_author_image'),
    ]

    operations = [
        # All operations wrapped in SeparateDatabaseAndState since schema already exists
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='articlepage',
                    name='author',
                    field=models.CharField(blank=True, help_text='Author name (legacy - use Author Profile instead)', max_length=100),
                ),
                migrations.AlterField(
                    model_name='articlepage',
                    name='author_image',
                    field=models.ForeignKey(blank=True, help_text='Author profile picture (legacy - use Author Profile instead)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
                ),
                migrations.AlterField(
                    model_name='blogpage',
                    name='author',
                    field=models.CharField(blank=True, help_text='Author name (legacy - use Author Profile instead)', max_length=100),
                ),
                migrations.AlterField(
                    model_name='blogpage',
                    name='author_image',
                    field=models.ForeignKey(blank=True, help_text='Author profile picture (legacy - use Author Profile instead)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
                ),
                migrations.CreateModel(
                    name='Author',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(help_text="Author's full name", max_length=100, unique=True)),
                        ('job_title', models.CharField(blank=True, help_text="Author's job title or role", max_length=200)),
                        ('bio', models.TextField(blank=True, help_text='Short biography of the author')),
                        ('email', models.EmailField(blank=True, help_text="Author's email address", max_length=254)),
                        ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                        ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL')),
                        ('profile_image', models.ForeignKey(blank=True, help_text="Author's profile picture", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                    ],
                    options={
                        'ordering': ['name'],
                    },
                ),
                migrations.AddField(
                    model_name='articlepage',
                    name='author_profile',
                    field=models.ForeignKey(blank=True, help_text='Select an author from the Author database', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.author'),
                ),
                migrations.AddField(
                    model_name='blogpage',
                    name='author_profile',
                    field=models.ForeignKey(blank=True, help_text='Select an author from the Author database', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='blog.author'),
                ),
            ],
            database_operations=[],
        ),
    ]
