# Generated by Django 4.2.7 on 2026-01-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_add_author_model'),
        ('blog', '0005_alter_articlepage_author_and_more'),
    ]

    operations = [
    ]
