# Generated by Django 4.2.7 on 2026-01-14 15:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('blog', '0006_merge_20260114_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyCashMattersFeaturePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.CharField(default='Why Cash Matters', help_text='Main page title', max_length=255)),
                ('page_date', models.CharField(blank=True, default='Apr 1, 2025', help_text='Display date', max_length=100)),
                ('intro_text', models.TextField(help_text='Introduction paragraph')),
                ('feature_cards', wagtail.fields.StreamField([('card', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Card title', required=True)), ('description', wagtail.blocks.TextBlock(help_text='Card description', required=True)), ('icon_type', wagtail.blocks.CharBlock(help_text='Icon type: svg, emoji, or image', required=False)), ('icon_svg_code', wagtail.blocks.TextBlock(help_text='SVG code for the icon (if icon_type is svg)', required=False)), ('icon_emoji', wagtail.blocks.CharBlock(help_text='Emoji character (if icon_type is emoji)', max_length=10, required=False)), ('icon_image', wagtail.images.blocks.ImageChooserBlock(help_text='Upload icon image (if icon_type is image)', required=False)), ('color', wagtail.blocks.CharBlock(choices=[('blue', 'Blue'), ('red', 'Red'), ('gold', 'Gold'), ('green', 'Green')], default='blue', help_text='Icon color theme', required=False)), ('card_size', wagtail.blocks.CharBlock(choices=[('large', 'Large (Top Featured)'), ('small', 'Small (Bottom Grid)')], default='small', help_text='Card size', required=False))]))], blank=True, help_text='Add feature cards (first 2 will be large, rest will be in bottom grid)', use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='twitter_handle',
        ),
        migrations.RemoveField(
            model_name='author',
            name='website',
        ),
        migrations.AddField(
            model_name='author',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='author',
            field=models.CharField(blank=True, help_text='Author name (legacy - use Author Profile instead)', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(help_text="Author's full name", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='author',
            field=models.CharField(blank=True, help_text='Author name (legacy - use Author Profile instead)', max_length=100),
        ),
    ]
