# Generated by Django 4.2.7 on 2026-01-15 17:08

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_whycashmattersfeaturepage_alter_author_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whycashmattersfeaturepage',
            name='feature_cards',
            field=wagtail.fields.StreamField([('card', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Card title', required=True)), ('description', wagtail.blocks.TextBlock(help_text='Card description', required=True)), ('icon_type', wagtail.blocks.CharBlock(help_text='Icon type: svg, emoji, or image', required=False)), ('icon_svg_code', wagtail.blocks.TextBlock(help_text='SVG code for the icon (if icon_type is svg)', required=False)), ('icon_emoji', wagtail.blocks.CharBlock(help_text='Emoji character (if icon_type is emoji)', max_length=10, required=False)), ('icon_image', wagtail.images.blocks.ImageChooserBlock(help_text='Upload icon image (if icon_type is image)', required=False)), ('modal_image', wagtail.images.blocks.ImageChooserBlock(help_text='Background image for modal popup (optional)', required=False)), ('color', wagtail.blocks.CharBlock(choices=[('blue', 'Blue'), ('red', 'Red'), ('gold', 'Gold'), ('green', 'Green')], default='blue', help_text='Icon color theme', required=False)), ('card_size', wagtail.blocks.CharBlock(choices=[('large', 'Large (Top Featured)'), ('small', 'Small (Bottom Grid)')], default='small', help_text='Card size', required=False))]))], blank=True, help_text='Add feature cards (first 2 will be large, rest will be in bottom grid)', use_json_field=True),
        ),
    ]
