# Generated by Django 6.0.2 on 2026-02-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_whycashmattersfeaturepage_feature_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='cover_story',
            field=models.BooleanField(default=False, help_text='Cover Story'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='editors_pick',
            field=models.BooleanField(default=False, help_text="Editor's Pick"),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='cover_story',
            field=models.BooleanField(default=False, help_text='Cover Story'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='editors_pick',
            field=models.BooleanField(default=False, help_text="Editor's Pick"),
        ),
    ]
