# Generated by Django 6.0.2 on 2026-02-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_articlepage_cover_story_articlepage_editors_pick_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletype',
            name='name',
            field=models.CharField(choices=[("Editor's Pick", "Editor's Pick"), ('Key Facts', 'Key Facts'), ('News', 'News'), ('Stories', 'Stories'), ('Podcast', 'Podcast'), ('Interview', 'Interview'), ('Studies and Report', 'Studies and Report')], max_length=100, unique=True),
        ),
    ]
