# Generated by Django 6.0.2 on 2026-02-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_articlepage_body_alter_blogpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
