# Generated by Django 6.0.2 on 2026-02-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_poll_options_remove_poll_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollchoice',
            old_name='text',
            new_name='question',
        ),
        migrations.AddField(
            model_name='pollchoice',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
