# Generated by Django 6.0.2 on 2026-02-12 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_rename_text_pollchoice_question_pollchoice_votes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyfactspage',
            name='alternative_text',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='keyfactspage',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='keyfactspage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Post date'),
        ),
        migrations.AddField(
            model_name='keyfactspage',
            name='double_width',
            field=models.BooleanField(default=False, help_text='Make a thumbnail double width on the home page. Must have a wide thumbnail.'),
        ),
        migrations.AddField(
            model_name='keyfactspage',
            name='fact_source',
            field=models.CharField(blank=True, help_text='The cited source for the fact', max_length=255),
        ),
        migrations.AddField(
            model_name='keyfactspage',
            name='featured_data',
            field=models.CharField(blank=True, help_text='This is the large featured number used on key fact cards', max_length=50),
        ),
        migrations.AddField(
            model_name='keyfactspage',
            name='featured_data_color',
            field=models.CharField(blank=True, help_text='The color for the feature. White will be used if not selected', max_length=50),
        ),
        migrations.AddField(
            model_name='keyfactspage',
            name='page_header_image',
            field=models.ForeignKey(blank=True, help_text='Choose an image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='keyfactspage',
            name='page_header_title',
            field=models.CharField(blank=True, help_text='Optional. If nothing is entered, the page title will be used.', max_length=255),
        ),
        migrations.AddField(
            model_name='keyfactspage',
            name='source_link',
            field=models.URLField(blank=True, help_text="Link to the article's source, if any."),
        ),
        migrations.AddField(
            model_name='keyfactspage',
            name='twitter_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='keyfactspage',
            name='vimeo_id',
            field=models.CharField(blank=True, help_text='The Vimeo Video ID (the number at the end of the video url)', max_length=50),
        ),
        migrations.AlterField(
            model_name='keyfactspage',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='keyfactspage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='keyfactspage',
            name='key_facts',
            field=models.TextField(blank=True),
        ),
    ]
