# Generated by Django 6.0.2 on 2026-02-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_keyfactspage_article_types_keyfactspage_body_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from name if left blank', max_length=120, unique=True),
        ),
    ]
