# Generated by Django 6.0.2 on 2026-02-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_sector_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandAssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tag_colour', models.CharField(blank=True, help_text='Optional: Tag will appear grey if a colour is not chosen.', max_length=20)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
