# Generated by Django 4.2.7 on 2026-02-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_brandassettag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='vimeo_id',
            field=models.CharField(blank=True, help_text='Vimeo Video ID', max_length=50, verbose_name='Vimeo ID'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from name if left blank', max_length=120, null=True, unique=True),
        ),
    ]
