# Generated by Django 4.2.7 on 2026-02-13 10:57

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_blogpage_vimeo_id_alter_sector_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='alternative_text',
            field=models.CharField(blank=True, help_text='Alternative Text', max_length=250, verbose_name='Alternative Text'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='cm_watermark',
            field=models.BooleanField(default=False, help_text='CM Watermark?', verbose_name='CM Watermark'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='page_header',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional page header content', verbose_name='Page Header'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='source_link',
            field=models.URLField(blank=True, help_text="Link to the article's source", verbose_name='Source link'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='vimeo_id',
            field=models.CharField(blank=True, help_text='The Vimeo Video ID (the number at the end of the video url)', max_length=50, verbose_name='Vimeo ID'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='alternative_text',
            field=models.CharField(blank=True, help_text='Alternative Text', max_length=250, verbose_name='Alternative Text'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='cm_watermark',
            field=models.BooleanField(default=False, help_text='CM Watermark?', verbose_name='CM Watermark'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='page_header',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional page header content', verbose_name='Page Header'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='source_link',
            field=models.URLField(blank=True, help_text="Link to the article's source", verbose_name='Source link'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='vimeo_id',
            field=models.CharField(blank=True, help_text='The Vimeo Video ID (the number at the end of the video url)', max_length=50, verbose_name='Vimeo ID'),
        ),
        migrations.AlterField(
            model_name='keyfactspage',
            name='source_link',
            field=models.URLField(blank=True, help_text="Link to the article's source, if any.", verbose_name='Source link'),
        ),
        migrations.AlterField(
            model_name='whycashmatterspage',
            name='alternative_text',
            field=models.CharField(blank=True, help_text='Alternative Text', max_length=250, verbose_name='Alternative Text'),
        ),
        migrations.AlterField(
            model_name='whycashmatterspage',
            name='cm_watermark',
            field=models.BooleanField(default=False, help_text='CM Watermark?', verbose_name='CM Watermark'),
        ),
        migrations.AlterField(
            model_name='whycashmatterspage',
            name='page_header',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional page header content', verbose_name='Page Header'),
        ),
        migrations.AlterField(
            model_name='whycashmatterspage',
            name='source_link',
            field=models.URLField(blank=True, help_text="Link to the article's source", verbose_name='Source link'),
        ),
        migrations.AlterField(
            model_name='whycashmatterspage',
            name='vimeo_id',
            field=models.CharField(blank=True, help_text='The Vimeo Video ID (the number at the end of the video url)', max_length=50, verbose_name='Vimeo ID'),
        ),
    ]
