# Generated by Django 4.2.7 on 2026-02-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_articlepage_alternative_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='source_link',
            field=models.URLField(blank=True, help_text="Link to the article's source", verbose_name='Source Link'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='source_link',
            field=models.URLField(blank=True, help_text="Link to the article's source", verbose_name='Source Link'),
        ),
        migrations.AlterField(
            model_name='keyfactspage',
            name='source_link',
            field=models.URLField(blank=True, help_text="Link to the article's source, if any.", verbose_name='Source Link'),
        ),
        migrations.AlterField(
            model_name='whycashmatterspage',
            name='source_link',
            field=models.URLField(blank=True, help_text="Link to the article's source", verbose_name='Source Link'),
        ),
    ]
