# Generated by Django 4.2.7 on 2026-02-13 18:13

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_articlepage_source_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('content', 1), ('image_caption', 4), ('video_caption', 6), ('iframe_caption', 10), ('blockquote', 12), ('data_table', 16), ('poll', 18), ('facts_carousel', 21), ('key_fact_image', 23)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 1: ('wagtail.blocks.StructBlock', [[('content', 0)]], {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {}), 5: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste YouTube/Vimeo URL', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('video', 5), ('caption', 3)]], {}), 7: ('wagtail.blocks.URLBlock', (), {'required': True}), 8: ('wagtail.blocks.IntegerBlock', (), {'default': 480, 'required': True}), 9: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Align caption with bottom of iframe?', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('iframe_url', 7), ('iframe_height', 8), ('caption', 3), ('align_caption_bottom', 9)]], {}), 11: ('wagtail.blocks.TextBlock', (), {'required': True}), 12: ('wagtail.blocks.StructBlock', [[('name', 3), ('job_title', 3), ('company', 3), ('quote_text', 11)]], {}), 13: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'required': True}), 14: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No headers'), ('row', 'First row'), ('column', 'First column'), ('both', 'First row and first column')], 'help_text': 'Which cells should be displayed as headers?', 'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'A heading that identifies the overall topic of the table, useful for screen reader users.', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('title', 3), ('table', 13), ('table_headers', 14), ('table_caption', 15)]], {}), 17: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'help_text': 'Choose Poll', 'required': True, 'target_model': 'blog.Poll'}), 18: ('wagtail.blocks.StructBlock', [[('poll', 17)]], {}), 19: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['blog.BlogPage']}), 20: ('wagtail.blocks.ListBlock', (19,), {'required': True}), 21: ('wagtail.blocks.StructBlock', [[('slides', 20)]], {}), 22: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Choose a page (Blog Page - Key Facts)', 'page_type': ['blog.KeyFactsPage'], 'required': True}), 23: ('wagtail.blocks.StructBlock', [[('key_fact_page', 22)]], {})}),
        ),
    ]
