# Generated by Django 4.2.7 on 2026-02-13 18:15

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('content', 1), ('image_caption', 7), ('video_caption', 10), ('iframe_caption', 14), ('blockquote', 16), ('data_table', 20), ('poll', 22), ('facts_carousel', 25), ('key_fact_image', 27)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 1: ('wagtail.blocks.StructBlock', [[('content', 0)]], {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Align caption with bottom of image?', 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Choose a page', 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'help_text': 'External link', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('align_caption_bottom', 4), ('internal_link', 5), ('external_link', 6)]], {}), 8: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Paste YouTube or Vimeo URL', 'required': True}), 9: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Align caption with bottom of video?', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('video_url', 8), ('caption', 3), ('align_caption_bottom', 9), ('internal_link', 5), ('external_link', 6)]], {}), 11: ('wagtail.blocks.URLBlock', (), {'required': True}), 12: ('wagtail.blocks.IntegerBlock', (), {'default': 480, 'required': True}), 13: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Align caption with bottom of iframe?', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('iframe_url', 11), ('iframe_height', 12), ('caption', 3), ('align_caption_bottom', 13)]], {}), 15: ('wagtail.blocks.TextBlock', (), {'required': True}), 16: ('wagtail.blocks.StructBlock', [[('name', 3), ('job_title', 3), ('company', 3), ('quote_text', 15)]], {}), 17: ('wagtail.contrib.table_block.blocks.TableBlock', (), {'required': True}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('none', 'No headers'), ('row', 'First row'), ('column', 'First column'), ('both', 'First row and first column')], 'help_text': 'Which cells should be displayed as headers?', 'required': False}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'A heading that identifies the overall topic of the table, useful for screen reader users.', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('title', 3), ('table', 17), ('table_headers', 18), ('table_caption', 19)]], {}), 21: ('wagtail.snippets.blocks.SnippetChooserBlock', (), {'help_text': 'Choose Poll', 'required': True, 'target_model': 'blog.Poll'}), 22: ('wagtail.blocks.StructBlock', [[('poll', 21)]], {}), 23: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['blog.BlogPage']}), 24: ('wagtail.blocks.ListBlock', (23,), {'required': True}), 25: ('wagtail.blocks.StructBlock', [[('slides', 24)]], {}), 26: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Choose a page (Blog Page - Key Facts)', 'page_type': ['blog.KeyFactsPage'], 'required': True}), 27: ('wagtail.blocks.StructBlock', [[('key_fact_page', 26)]], {})}),
        ),
    ]
