# Generated by Django 4.2.7 on 2026-02-13 18:46

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='double_width',
            field=models.BooleanField(default=False, help_text='Make a thumbnail double width on the home page. Must have a wide thumbnail.'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='featured',
            field=models.BooleanField(default=False, help_text='To feature a post, ensure it has tall thumbnail.'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='hide_title',
            field=models.BooleanField(default=False, help_text="Hide the post title when you're using text within your thumbnail."),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='source_link',
            field=models.URLField(blank=True, help_text="Link to the article's source, if any.", verbose_name='Source Link'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='white_text',
            field=models.BooleanField(default=False, help_text='Toggle the icons and text to white, perfect for darker images.'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='double_width',
            field=models.BooleanField(default=False, help_text='Make a thumbnail double width on the home page. Must have a wide thumbnail.'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='featured',
            field=models.BooleanField(default=False, help_text='To feature a post, ensure it has tall thumbnail.'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='hide_title',
            field=models.BooleanField(default=False, help_text="Hide the post title when you're using text within your thumbnail."),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='page_header',
            field=wagtail.fields.RichTextField(blank=True, help_text='Optional. If nothing is entered, the page title will be used.', verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='source_link',
            field=models.URLField(blank=True, help_text="Link to the article's source, if any.", verbose_name='Source Link'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='white_text',
            field=models.BooleanField(default=False, help_text='Toggle the icons and text to white, perfect for darker images.'),
        ),
        migrations.AlterField(
            model_name='whycashmatterspage',
            name='double_width',
            field=models.BooleanField(default=False, help_text='Make a thumbnail double width on the home page. Must have a wide thumbnail.'),
        ),
        migrations.AlterField(
            model_name='whycashmatterspage',
            name='featured',
            field=models.BooleanField(default=False, help_text='To feature a post, ensure it has tall thumbnail.'),
        ),
        migrations.AlterField(
            model_name='whycashmatterspage',
            name='hide_title',
            field=models.BooleanField(default=False, help_text="Hide the post title when you're using text within your thumbnail."),
        ),
        migrations.AlterField(
            model_name='whycashmatterspage',
            name='source_link',
            field=models.URLField(blank=True, help_text="Link to the article's source, if any.", verbose_name='Source Link'),
        ),
        migrations.AlterField(
            model_name='whycashmatterspage',
            name='white_text',
            field=models.BooleanField(default=False, help_text='Toggle the icons and text to white, perfect for darker images.'),
        ),
    ]
