# Generated by Django 4.2.7 on 2026-02-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_articlepage_double_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='cover_story',
            field=models.BooleanField(default=False, help_text='Display this post as a main cover story.'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='editors_pick',
            field=models.BooleanField(default=False, help_text='Feature this post in the Editor’s Pick section.'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='cover_story',
            field=models.BooleanField(default=False, help_text='Display this post as a main cover story.'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='editors_pick',
            field=models.BooleanField(default=False, help_text='Feature this post in the Editor’s Pick section.'),
        ),
    ]
