# Generated by Django 4.2.7 on 2026-02-16 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('blog', '0029_alter_articlepage_cover_story_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description (social share description)'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Open Graph image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title (social share title)', max_length=255),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description (social share description)'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Open Graph image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title (social share title)', max_length=255),
        ),
    ]
