FROM python:3.12-slim

# Set workdir
WORKDIR /cashmatters

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Collect static files
RUN python manage.py collectstatic --noinput

# Expose port for Gunicorn
EXPOSE 8000

# Run Gunicorn
CMD ["gunicorn", "cashmatters.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]
